# -*- coding: utf-8 -*-
"""hackthon_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hhq3QUluOk6kYNOEORCUhF_t0iEXBXA6
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

train = pd.read_csv('/content/train_LZdllcl.csv')
test = pd.read_csv('/content/test_2umaH9m (1).csv')

train.shape, test.shape

train.dtypes

train.info()

train.head(3)

train.columns[train.isna().any()]

na_cols = train.columns[train.isna().any()]

train.isna().sum()[train.isna().sum() > 0].index.tolist()

train.isna().sum()[train.isna().sum() > 0]

train[na_cols].isna().sum()/train.shape[0]*100

(train[na_cols].isna().sum()/train.shape[0]*100).sort_values()

train['education'].value_counts()

train.education.value_counts()

train.columns

train['previous_year_rating'].value_counts()

train.education.value_counts().plot(kind='bar')

num_col = ['age', 'previous_year_rating','avg_training_score']
num_col

cat_col = ['department','region','education','gender','recruitment_channel']
cat_col

from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score,f1_score

cat_pipe_enc = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ohe', OneHotEncoder(handle_unknown='ignore'))
])
cat_pipe_enc

num_pipe_enc = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')), # missing values
    ('scaler', StandardScaler()) # standardization
])
num_pipe_enc

preprocess = ColumnTransformer(transformers=[
    ('cat_enc', cat_pipe_enc, cat_col),
    ('num_enc', num_pipe_enc, num_col)
    ])

from sklearn.linear_model import LinearRegression

model_pipeline = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', LinearRegression())
])

model_pipeline

x=train.drop(['employee_id','is_promoted'],axis=1)
y=train['is_promoted']

X['previous_year_rating'].fillna(0, inplace=True)

# categorical
X['education'].fillna('Unknown', inplace=True)

X = pd.get_dummies(X, drop_first=True)

# apply same columns to test
test_ids = test['employee_id']
test = test.drop('employee_id', axis=1)
test['previous_year_rating'].fillna(0, inplace=True)
test['education'].fillna('Unknown', inplace=True)
test = pd.get_dummies(test, drop_first=True)

# align columns
X, test = X.align(test, join='left', axis=1, fill_value=0)

X.head(2),y.head(2)

from sklearn.model_selection import train_test_split

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=8,
    random_state=42,
    class_weight='balanced'
)

model.fit(X_train, y_train)

model_pipeline.fit(train_X, train_y)

from sklearn.metrics import f1_score

y_pred = model.predict(X_val)

f1 = f1_score(y_val, y_pred)
print("F1 Score:", f1)

y_prob = model.predict_proba(X_val)[:, 1]

for t in [0.3, 0.35, 0.4, 0.45, 0.5]:
    preds = (y_prob >= t).astype(int)
    print(t, f1_score(y_val, preds))

test_prob = model.predict_proba(test)[:, 1]
test_pred = (test_prob >= 0.4).astype(int)

submission = pd.DataFrame({
    'employee_id': test_ids,
    'is_promoted': test_pred
})

submission.to_csv('submission.csv', index=False)